### ISSUE TITLE
SGE: qsub: command required for a binary job

### ISSUE THREAD

**Issue by floerhard** [pcingola/BigDataScript#51]
Dear Pablo,

first of all, nice work, bds looks like a really nice platform to build pipelines on!

I wanted to try a minimal example (Hello World with 'task') on our SGE cluster using BigDataScript 0.99c (build 2014-12-15)

```
#!/usr/bin/env bds
task echo Hello world
```

```
bds -system sge -debug -l -v hello_world.bds
```

The output is
```
00:00:00.214	Executioner: ExecutionerClusterSge, task hello_world.bds.20141219_114332_240/task.line_3.id_1
00:00:00.214	Running command: echo "bds exec 86400 '/home/users/erhard/test/bds/hello_world.bds.20141219_114332_240/task.line_3.id_1.stdout' '/home/users/erhard/test/bds/hello_world.bds.20141219_114332_240/task.line_3.id_1.stderr' '/home/users/erhard/test/bds/hello_world.bds.20141219_114332_240/task.line_3.id_1.exitCode' '/home/users/erhard/test/bds/hello_world.bds.20141219_114332_240/task.line_3.id_1.sh' " | qsub -pe serial 1 -o /home/users/erhard/test/bds/hello_world.bds.20141219_114332_240/task.line_3.id_1.stdout.cluster -e /home/users/erhard/test/bds/hello_world.bds.20141219_114332_240/task.line_3.id_1.stderr.cluster 
00:00:00.215	Command (CmdCluster): CmdCluster: qsub -pe serial 1 -o /home/users/erhard/test/bds/hello_world.bds.20141219_114332_240/task.line_3.id_1.stdout.cluster -e /home/users/erhard/test/bds/hello_world.bds.20141219_114332_240/task.line_3.id_1.stderr.cluster 
00:00:00.216	CmdCluster 'hello_world.bds.20141219_114332_240/task.line_3.id_1': Start
00:00:00.216	ExecutionerClusterSge 'ClusterSge[11]': Queue: No task to run.
00:00:00.216	CmdLocal: Executing  qsub -pe serial 1 -o /home/users/erhard/test/bds/hello_world.bds.20141219_114332_240/task.line_3.id_1.stdout.cluster -e /home/users/erhard/test/bds/hello_world.bds.20141219_114332_240/task.line_3.id_1.stderr.cluster
WARNING: Process closed stdout prematurely. Could not read PID
CmdCluster: qsub -pe serial 1 -o /home/users/erhard/test/bds/hello_world.bds.20141219_114332_240/task.line_3.id_1.stdout.cluster -e /home/users/erhard/test/bds/hello_world.bds.20141219_114332_240/task.line_3.id_1.stderr.cluster 
qsub: command required for a binary job
```

Is the shell script is missing from the qsub call?

Best,
Florian

**Comment by pcingola** [comment]
The output says:
    Regex '"Your job (\d+)"' did NOT match line: Your job 18157 ("STDIN") has been submitted

I think the backslash should be escaped, so it should be (notice the double backslash):

     pidRegex = "Your job (\\d+)"

Let me know if it helps.
In any case, bds should show an intuitive error message and exit (I'll make sure to fix it for the next version).

**Comment by floerhard** [comment]
Dear Pablo,

I think my problem is different from golharam's. In my environment, qsub rejects the command from stdin (I oversaw the pipe before). 

If I, as you suggested, do the "echo ... | qsub ..." manually, i get the message:
qsub: command required for a binary job

I think this stems from the parameter '-b y' that is presumably configured in our environment by default. If I override it and call "... | qsub -b n ...", I get:
Unable to run job: job 8105270 was rejected cause it can't be written: No such file or directory.
Exiting.

Is it necessary to pipe the command into qsub? Why don't you just append it to the qsub call?

Best,
Florian

**Comment by golharam** [comment]
Yes, I verified my regex is:

pidRegex = "Your job (\\d+)"

**Comment by pcingola** [comment]
@golharam So it works without the double backslash? 
Here is the one I use for my SGE cluster:

    pidRegex = "Your job (\\S+)"

Let me know if it works for you.

**Comment by pcingola** [comment]
@floerhard 
In most clusters, qsub cannot execute arbitrary commands (qsub can only execute scripts):

    $ qsub date
    qsub: script file 'date' cannot be loaded - No such file or directory

The standard way to feed qsub a command is to feed into STDIN:

    $ echo date | qsub
    # OK

This is why I use STDIN.

**Comment by golharam** [comment]
It looks like github is mangling my comments.  My regex has a double backslash and BDS is not matching my regex.  I'm using the same regex you specified for SGE.

**Comment by pcingola** [comment]
@golharam 
I've added a new command line option '-checkPidRegex', here is how to use it:

    $ echo "Your job 18157" | bds -checkPidRegex
    Matching pidRegex 'Your job (\S+)'
    Input line:	'Your job 18157'	Pid regex matched '18157'

    $ echo "Should not match 18157" | bds -checkPidRegex
    Matching pidRegex 'Your job (\S+)'
    Input line:	'Should not match 18157'	Pid regex did not match

Thanks to the log you sent, I discovered that I introduced a bug 
when parsing the pid regex expression. Now the has been 
fixed (version 0.999b). Thank you! (and apologies for the bug).

Please let me know if it works OK for you.

**Comment by golharam** [comment]
It looks like -checkPidRegex is working.  But something is still wrong.  My
script has 1 line:

task echo Hello world, task

When I run the script using the command 'bds -s sge test.bds', I see the
job get submitted to SGE and I see it complete, but bds never sees the job
complete.  I have to Ctrl-C to stop bds.  Here's the debug log:

00:00:00.000 BigDataScript 0.999b (build 2015-01-08), by Pablo Cingolani
00:00:00.007 BigDataScript: Initialize global scope.
00:00:00.038 BigDataScript: Initialize standard libraries.
00:00:00.058 BigDataScript: Native library:
NativeLibraryFunctions:
  FunctionNativePrint
  FunctionNativePrintErr
  FunctionNativeMinInt
  FunctionNativeMaxInt
  FunctionNativeMinReal
  FunctionNativeMaxReal
  FunctionNativeRand
  FunctionNativeRandInt
  FunctionNativeRandIntRange
  FunctionNativeRandSeed
  FunctionNativeRangeInt
  FunctionNativeRangeIntStep
  FunctionNativeRangeReal
  FunctionNativeSleep
  FunctionNativeSleepReal
  FunctionNativeToIntFromBool
  FunctionNativeToIntFromReal
  FunctionNativeConfig
  FunctionNativeConfigOri

00:00:00.089 BigDataScript: Native library:
NativeLibraryString:
  MethodNative_string_length
  MethodNative_string_toUpper
  MethodNative_string_toLower
  MethodNative_string_trim
  MethodNative_string_substr_start_end
  MethodNative_string_substr_start
  MethodNative_string_split_regex
  MethodNative_string_lines
  MethodNative_string_isEmpty
  MethodNative_string_startsWith_str
  MethodNative_string_endsWith_str
  MethodNative_string_indexOf_str
  MethodNative_string_lastIndexOf_str
  MethodNative_string_replace_str1_str2
  MethodNative_string_parseInt
  MethodNative_string_parseReal
  MethodNative_string_parseBool
  MethodNative_string_replace_regex_repl
  MethodNative_string_path
  MethodNative_string_baseName
  MethodNative_string_baseName_ext
  MethodNative_string_dirName
  MethodNative_string_pathName
  MethodNative_string_extName
  MethodNative_string_canRead
  MethodNative_string_canWrite
  MethodNative_string_canExec
  MethodNative_string_exists
  MethodNative_string_isDir
  MethodNative_string_isFile
  MethodNative_string_delete
  MethodNative_string_rm
  MethodNative_string_mkdir
  MethodNative_string_read
  MethodNative_string_removeExt
  MethodNative_string_removeExt_ext
  MethodNative_string_rmOnExit
  MethodNative_string_swapExt_extNew
  MethodNative_string_swapExt_extOld_extNew
  MethodNative_string_write_str
  MethodNative_string_readLines
  MethodNative_string_dir
  MethodNative_string_dir_regex
  MethodNative_string_dirPath
  MethodNative_string_dirPath_regex
  MethodNative_string_size
  MethodNative_string_isDone
  MethodNative_string_isDoneOk
  MethodNative_string_stdout
  MethodNative_string_stderr
  MethodNative_string_exitCode

00:00:00.096 Parsing
00:00:00.096 BigDataScript: Loading file: 'test.bds'
00:00:00.096 BigDataScript: Creating AST.
00:00:00.387 AST:
     Child 0: [28] Tree:'([28] \n \n)'
     Child 1: [34] Tree:'([34] print ([144 34] "Hello world\n") ([147 34]
\n \n))'
     Child 2: [34] Tree:'([34] ([314 34] sys echo Hello world, sys) ([315
34] \n \n))'
     Child 3: [34] Tree:'([34] ([314 34] task echo Hello world, task) ([315
34] \n \n))'
00:00:00.390 BigDataScript: Creating BigDataScript tree.
00:00:00.426 BigDataScript: AST:
print "Hello world\n"

sys  echo Hello world, sys
task  "echo Hello world, task"

00:00:00.427 BigDataScript: Type checking.
00:00:00.430 Initializing
00:00:00.449 Process ID: test.bds.20150109_122430_716
00:00:00.449 Running
Hello world
Hello world, sys
00:00:00.470 Executioner factory: Creating new executioner type 'SGE'
00:00:00.483 ExecutionerClusterSge: Using pidRegex 'Your job (\d+)'
00:00:00.485 ExecutionerClusterSge: Using pidRegex 'Your job (\d+)'
00:00:00.486 ExecutionerClusterSge 'ClusterSge[12]': Queuing task:
test.bds.20150109_122430_716/task.line_7.id_2
00:00:00.486 ExecutionerClusterSge 'ClusterSge[12]': Started running
00:00:00.487 BdsThread finished: test.bds.20150109_122430_716
00:00:00.487 Program 'test.bds.20150109_122430_716' execution finished
00:00:00.489 Waiting for all tasks to finish.
00:00:00.489 Wait: Waiting for task to finish:
test.bds.20150109_122430_716/task.line_7.id_2
Executioner.selectTask(516): TASK ID:
test.bds.20150109_122430_716/task.line_7.id_2 Hint: echo Hello world, task
  HOST                : localhost
  RESOURCES AVAILABLE : cpus: 2147483647 mem: 8192.0 PB
  TASK RESOURCES      : cpus: 1 mem: -1.0 B  timeout: 86400  wall-timeout:
86400
00:00:00.493 ExecutionerClusterSge 'ClusterSge[12]': Task selected
'test.bds.20150109_122430_716/task.line_7.id_2' on host 'localhost'
00:00:00.497 Task: Saving file
'/home/golharr/workspace/BigDataScript/examples/test.bds.20150109_122430_716/
task.line_7.id_2.sh'
00:00:00.501 Executioner: ExecutionerClusterSge, task
test.bds.20150109_122430_716/task.line_7.id_2
00:00:00.502 Running command: echo "bds exec 86400
'/home/golharr/workspace/BigDataScript/examples/test.bds.20150109_122430_716/task.line_7.id_2.stdout'
'/home/golharr/workspace/BigDataScript/examples/test.bds.20150109_122430_716/task.line_7.id_2.stderr'
'/home/golharr/workspace/BigDataScript/examples/test.bds.20150109_122430_716/task.line_7.id_2.exitCode'
'/home/golharr/workspace/BigDataScript/examples/test.bds.20150109_122430_716/
task.line_7.id_2.sh' " | qsub -pe pe 1 -o
/home/golharr/workspace/BigDataScript/examples/test.bds.20150109_122430_716/task.line_7.id_2.stdout.cluster
-e
/home/golharr/workspace/BigDataScript/examples/test.bds.20150109_122430_716/task.line_7.id_2.stderr.cluster

00:00:00.505 Command (CmdCluster): CmdCluster: qsub -pe pe 1 -o
/home/golharr/workspace/BigDataScript/examples/test.bds.20150109_122430_716/task.line_7.id_2.stdout.cluster
-e
/home/golharr/workspace/BigDataScript/examples/test.bds.20150109_122430_716/task.line_7.id_2.stderr.cluster

00:00:00.506 ExecutionerClusterSge 'ClusterSge[12]': Queue: No task to run.
00:00:00.506 CmdCluster 'test.bds.20150109_122430_716/task.line_7.id_2':
Start
00:00:00.508 CmdLocal: Executing  qsub -pe pe 1 -o
/home/golharr/workspace/BigDataScript/examples/test.bds.20150109_122430_716/task.line_7.id_2.stdout.cluster
-e
/home/golharr/workspace/BigDataScript/examples/test.bds.20150109_122430_716/task.line_7.id_2.stderr.cluster
00:00:00.542 CmdCluster 'test.bds.20150109_122430_716/task.line_7.id_2':
Reading PID line 'Your job 18281 ("STDIN") has been submitted'
00:00:00.543 ExecutionerCluster: Regex 'Your job (\d+)' matched '18281' in
line: Your job 18281 ("STDIN") has been submitted
00:00:00.544 CmdCluster 'test.bds.20150109_122430_716/task.line_7.id_2':
Running
00:00:00.545 CmdCluster 'test.bds.20150109_122430_716/task.line_7.id_2':
Done
00:00:01.007 ExecutionerClusterSge 'ClusterSge[12]': Task started
'test.bds.20150109_122430_716/task.line_7.id_2'
00:00:01.009 ExecutionerClusterSge 'ClusterSge[12]': Task running
'test.bds.20150109_122430_716/task.line_7.id_2'
00:00:01.010 TaskLogger: Appending to PidFile 'bds.pid.152080', lines:
     |18281 + qdel

00:00:01.016 Tail: Adding (TailFileMulti)
'/home/golharr/workspace/BigDataScript/examples/test.bds.20150109_122430_716/task.line_7.id_2.stdout'
00:00:01.016 Tail: Adding (TailFileMulti)
'/home/golharr/workspace/BigDataScript/examples/test.bds.20150109_122430_716/task.line_7.id_2.stderr'
00:00:01.017 MonitorTask: Adding task
test.bds.20150109_122430_716/task.line_7.id_2

**Comment by golharam** [comment]
Correction.  After sending the email, I see:

00:01:01.607 WARNING: Empty STDOUT when executing cluster stat command:
'qstat
00:01:02.131 Tasks [ClusterSge[12]]   Pending : 0 Running: 1 Done: 0
     | PID   | Task state        | Task name        | Dependencies | Task
definition        |
     | ----- | ----------------- | ---------------- | ------------ |
---------------------- |
     | 18281 | running (RUNNING) | task.line_7.id_2 |              | echo
Hello world, task |

**Comment by golharam** [comment]
Yeah, it looks like SGE is removing the completed jobs from the queue and
bds thinks the job is still running when in fact its not.

**Comment by pcingola** [comment]
@golharam 
When the task is completed in the slave node, bds-exec creates an 'exit' file.
In you case the file was 
 /home/golharr/workspace/BigDataScript/examples/test.bds.20150109_122430_716/task.line_7.id_2.exit

Was the file created successfully and visible from the head node (where you are running bds)? Try using the "-log" option to see if the files are created (if you don't use "-log" bds deletes them when execution finishes).

Another question: Is your cluster using NFS? I was told that some slow NFS systems take a few seconds to update file status...(as opposed to infiniband or other options).

**Comment by golharam** [comment]
No, there is no .exit file.  Here's what I have:

[golharr@kraken examples]$ ll
total 24
-rw------- 1 golharr bioinfo   13 Jan  9 12:45 bds.pid.44039
-rwxr-xr-x 1 golharr bioinfo  152 Jan  9 12:19 test.bds
drwxr-xr-x 2 golharr bioinfo 1024 Jan  9 12:45 test.bds.20150109_124519_400

[golharr@kraken examples]$ ll test.bds.20150109_124519_400/
total 16
-rwxr--r-- 1 golharr bioinfo  36 Jan  9 12:45 task.line_7.id_2.sh
-rw-r--r-- 1 golharr bioinfo   0 Jan  9 12:45
task.line_7.id_2.stderr.cluster
-rw-r--r-- 1 golharr bioinfo 135 Jan  9 12:45
task.line_7.id_2.stdout.cluster

**Comment by golharam** [comment]
Yes, this is an NFS file system, but the directory I'm operating in is
local for this particular node.  I know the problem you are describing too,
but that's not the case here.

**Comment by pcingola** [comment]
The "ls" doesn't show the stdout, stderr or 'exit' files...they should be there.
Are you sure the slave node can write in that dir?

There should be 5 files there:

    task.line_7.id_2.stdout
    task.line_7.id_2.stderr
    task.line_7.id_2.exitCode
    task.line_7.id_2.stdout.cluster
    task.line_7.id_2.stderr.cluster

The first three are the ones that bds-exec creates (and the oned bds needs to read). The last two files are create by the cluster system (bds ignores them).

**Comment by golharam** [comment]
'ls -alp' doesn't show them either:

[golharr@kraken test.bds.20150109_125709_059]$ ls -alp
total 32
drwxr-xr-x 2 golharr bioinfo 1024 Jan  9 12:57 ./
drwxr-xr-x 3 golharr bioinfo 1024 Jan  9 12:57 ../
-rwxr--r-- 1 golharr bioinfo   36 Jan  9 12:57 task.line_7.id_2.sh
-rw-r--r-- 1 golharr bioinfo    0 Jan  9 12:57
task.line_7.id_2.stderr.cluster
-rw-r--r-- 1 golharr bioinfo  135 Jan  9 12:57
task.line_7.id_2.stdout.cluster

**Comment by golharam** [comment]
There are two nodes in this cluster.  I'm running this from my home
directory and have run other jobs from my home directory as well so I know
its not a permission issue.

**Comment by pcingola** [comment]
If you are using the "-log" command line option AND the "slave process" can 
write in that directory (not a permission problem either), then I don't really 
know what's going on...

**Comment by pcingola** [comment]
Can you execute the "bds exec" command from the slave node and check that it writes the file appropriately? (many clusters do not allow acces to any slave nodes, so you probably can't).
The command is the one shown in the log (the one within the echo's quotes):

00:00:00.502 Running command: echo "bds exec 86400..."

Sorry to ask for all this, but I'm really puzzled...

**Comment by golharam** [comment]
Ah stupid stupid stupid.  It looks like SGE isn't taking my environment
settings so my .bds/ directory isn't in my path, hence bds is never
actually run.

**Comment by pcingola** [comment]
OK, that explains :-)

But I'm still puzzled. The "cluster" files should mention that error, but 
the "stderr.cluster" was empty...

Is there a chance that your cluster is configured to 
merge STDERR and STDOUT when using "-o" command 
line option in "qsub"? That could be the reason why you 
stderr.cluster file was empty...

**Comment by golharam** [comment]
My cluster doesn't merge stdout and stderr unless you specify it to using
the SGE param is '-j y'.

If I run the command from the shell:

qsub -pe pe 1 -o /home/golharr/test.out -e /home/golharr/test.err

then type 'bds' and press Ctrl-D, I see the errror in test.err in the
correct location.  How do I tell BDS to use bash instead of sh?  None of my
environment settings are set in sh, only in my .bashrc.

**Comment by golharam** [comment]
I think it might be better for BDS to put all the commands it wants to run
in a shell script that follows a user-defined or included shell template.
Then, no parameters are passed on the command line, everything is included
in the shell script.  It may make future debugging easier and allows user
to modify the job template shell script.

**Comment by pcingola** [comment]
I'm actually working on something like that...
The idea I was suing was to allow user defined scripts 
that call the cluster commands.

For the 'bash' instead of 'sh', I'll add a config option asap.

**Comment by pcingola** [comment]
Added 'taskShell' and 'sysShell' as options to bds.config file:

    # Task's shell
    #     WARNING: Make sure you use "-e" or some command line option that stops execution when an error if found.
    #taskShell = /bin/sh -e

    # Sys shell (or command execution shell)
    #    WARNING: Make sure you use "-e" or some command line option that stops execution when an error if found.
    #    WARNING: Make sure you use "-c" or some command line option that allows to provide a script
    #sysShell = /bin/sh -e -c

**Comment by golharam** [comment]
I pulled the changes but don't see a difference.  In my bds.config I have:

taskShell = /bin/bash -e

**Comment by pcingola** [comment]
Seems to work for me:

    # Here I run using the defaults:
    $ cat z.bds
    task echo Hi

    $ bds -log z.bds 
    Hi

    # Which shell was used?
    $ cat z.bds.20150109_154412_473/task.line_3.id_1.sh 
    #!/bin/sh -e

    echo Hi

Now I edit my ~/.bds/bds.config and change the task shell to 'bash'

    $ grep taskShell .bds/bds.config 
    taskShell = /bin/bash -e

Once the config file is changed, I re-run the script:

    $ bds -log z.bds 
    Hi

    # Which shell was used?
    $ cat z.bds.20150109_154545_479/task.line_3.id_1.sh 
    #!/bin/bash -e

    echo Hi


So the shell changed from '/bin/sh' to '/bin/bash'

**Comment by golharam** [comment]
OK, that's working, but not quite like I expected.  The new shell is taken
as bash, however SGE is still using /bin/sh.

The SGE parameter I use to force SGE to use bash in -S /bin/bash

I think the best fix would be to have every parameter that you can pass to
SGE as a parameters in the bds.config file or by creating a template shell
script file that bds uses for tasks.

**Comment by pcingola** [comment]
Yes, I'm working on that.
In the mean time, how about adding "SGE.parameters" to the config (a string that is passed directly qsub)

**Comment by golharam** [comment]
sure, ok.  SGE.parameters works (I think)

**Comment by kmhernan** [comment]
Somewhat related is the `qstat` function. I get errors using STARcluster with SGE:

```
00:00:35.528	Error trying to find out post-mortem info on task (PID '63').
	Exit code : 1
	Stdout    : 
	Stderr    : OGS/GE 2011.11p1
usage: qstat [options]
        [-cb]                             view additional binding specific parameters
        [-ext]                            view additional attributes
        [-explain a|c|A|E]                show reason for c(onfiguration ambiguous), a(larm), suspend A(larm), E(rror) state
        [-f]                              full output
        [-F [resource_attributes]]        full output and show (selected) resources of queue(s)
        [-g {c}]                          display cluster queue summary
        [-g {d}]                          display all job-array tasks (do not group)
        [-g {t}]                          display all parallel job tasks (do not group)
        [-help]                           print this help
        [-j job_identifier_list ]         show scheduler job information
        [-l resource_list]                request the given resources
        [-ne]                             hide empty queues
        [-pe pe_list]                     select only queues with one of these parallel environments
        [-q wc_queue_list]                print information on given queue
        [-qs {a|c|d|o|s|u|A|C|D|E|S}]     selects queues, which are in the given state(s)
        [-r]                              show requested resources of job(s)
        [-s {p|r|s|z|hu|ho|hs|hd|hj|ha|h|a}] show pending, running, suspended, zombie jobs,
                                          jobs with a user/operator/system/array-dependency hold, 
                                          jobs with a start time in future or any combination only.
                                          h is an abbreviation for huhohshdhjha
                                          a is an abbreviation for prsh
        [-t]                              show task information (implicitly -g t)
        [-u user_list]                    view only jobs of this user
        [-U user_list]                    select only queues where these users have access
        [-urg]                            display job urgency information
        [-pri]                            display job priority information
        [-xml]                            display the information in XML-Format

pe_list                  pe[,pe,...]
job_identifier_list      [job_id|job_name|pattern]{, [job_id|job_name|pattern]}
resource_list            resource[=value][,resource[=value],...]
user_list                user|@group[,user|@group],...]
resource_attributes      resource,resource,...
wc_cqueue                wildcard expression matching a cluster queue
wc_host                  wildcard expression matching a host
wc_hostgroup             wildcard expression matching a hostgroup
wc_qinstance             wc_cqueue@wc_host
wc_qdomain               wc_cqueue@wc_hostgroup
wc_queue                 wc_cqueue|wc_qdomain|wc_qinstance
wc_queue_list            wc_queue[,wc_queue,...]
invalid option argument "63"
```

I do have `-xml` available but I believe that on this machine you have to do `qstat -f -j JOB_ID`

**Comment by pcingola** [comment]
OK, added a config parameter called "clusterRunAdditionalArgs" (can be used for all cluster types, not only SGE).

Example, first using empty 'clusterRunAdditionalArgs' runs the same as before (output edited for readability):

    $ bds -s cluster -d z.bds
    ...
    00:00:00.269	Adding clusterRunAdditionalArgs. Number of additional arguments: 0
    ...
    00:00:00.280	Running command: echo "bds exec 86400 ..." | qsub -l nodes=1:ppn=1,walltime=24:02:00 

Now we change bds.config file:

    clusterRunAdditionalArgs = -A myUserName

and run again:

    $ bds -s cluster -d z.bds
    ....
    00:00:00.264	Adding clusterRunAdditionalArgs. Number of additional arguments: 2
    			0	'-A'
    			1	'myUserName'
    ...
    00:00:00.275	Running command: echo "bds exec 86400 ... " | qsub -A myUserName -l nodes=1:ppn=1,walltime=24:02:00 ...

As you can see, the '-A myUserName' was added to qsub's command line.

**Comment by pcingola** [comment]
@kmhernan 
I'm adding the same for all other commands: kill (qdel), stat (qstat), and postMortemInfo.
It will be ready soon.

**Comment by pcingola** [comment]
Added to bds.config file (see sample bds.config in 'config' dir): 
   clusterKillAdditionalArgs (qdel), 
   clusterStatAdditionalArgs (qstat) and 
   clusterPostMortemInfoAdditionalArgs (qstat -f)

Let me know how it works for you.

**Comment by golharam** [comment]
Looks like that worked.  I'll continue playing with it and keep you posted
if any issues come up.

BTW - I was trying to create something like BDS about a year or two ago.  I
ended up with something similar that would store the pipeline steps in an
XML file, and a module that would read the XML file, build an execution
tree, and execute each node on the tree on a cluster.  It was very similar
to Pegasis but without the overhead - it was a standalone Java app.

I didn't have the scripting language that you had, but instead had a series
of Java packages that could be used to write up an execution pipeline
similar to what your scripting language does.  I wonder if any of that code
could be useful to you.

**Comment by pcingola** [comment]
@golharam It would be interesting to take a look at it. Do you think some of the features in your package (currently missing from bds) could be added? If so, which ones?

**Comment by pcingola** [comment]
Added support for "generic cluster": It executes user defined script to run and kill tasks.

For details, take a look at "Generic Cluster options" in the "BDS Config file" documentation:
http://pcingola.github.io/BigDataScript/bigDataScript_manual.html#config

**Comment by golharam** [comment]
Maybe.  Its been a while since I looked at it but the cluster code was
pretty stable.  I'll dig it up today

**Comment by kmhernan** [comment]
@pcingola 

I added this to my config:

```
clusterPostMortemInfoAdditionalArgs = -j
clusterStatAdditionalArgs = -j
```

It appears to see it:

```
00:00:00.255	Executioner factory: Creating new executioner type 'SGE'
00:00:00.264	Parsing 'clusterStatAdditionalArgs'. Number of additional arguments: 1
			0	'-j'
00:00:00.264	Parsing 'clusterPostMortemInfoAdditionalArgs'. Number of additional arguments: 1
			0	'-j'
00:00:00.266	ExecutionerClusterSge: Using pidRegex 'Your job (\S+)'
00:00:00.267	ExecutionerClusterSge 'ClusterSge[11]': Queuing task: chk.bds.20150113_211735_625/task.line_1.id_1
00:00:00.267	ExecutionerClusterSge 'ClusterSge[11]': Started running
```

But I'm still getting the same results:

```
ExecutionerCluster.postMortemInfo(329):	Finding postMortemInfo for task chk.bds.20150113_211735_625/task.line_1.id_1: Command executed. Exit value 1. Stdout len: 0
00:00:01.294	Error trying to find out post-mortem info on task (PID '11').
	Exit code : 1
	Stdout    : 
	Stderr    : OGS/GE 2011.11p1
usage: qstat [options]
        [-cb]                             view additional binding specific parameters
        [-ext]                            view additional attributes
        [-explain a|c|A|E]                show reason for c(onfiguration ambiguous), a(larm), suspend A(larm), E(rror) state
        [-f]                              full output
        [-F [resource_attributes]]        full output and show (selected) resources of queue(s)
        [-g {c}]                          display cluster queue summary
        [-g {d}]                          display all job-array tasks (do not group)
        [-g {t}]                          display all parallel job tasks (do not group)
        [-help]                           print this help
        [-j job_identifier_list ]         show scheduler job information
        [-l resource_list]                request the given resources
        [-ne]                             hide empty queues
        [-pe pe_list]                     select only queues with one of these parallel environments
        [-q wc_queue_list]                print information on given queue
        [-qs {a|c|d|o|s|u|A|C|D|E|S}]     selects queues, which are in the given state(s)
        [-r]                              show requested resources of job(s)
        [-s {p|r|s|z|hu|ho|hs|hd|hj|ha|h|a}] show pending, running, suspended, zombie jobs,
                                          jobs with a user/operator/system/array-dependency hold, 
                                          jobs with a start time in future or any combination only.
                                          h is an abbreviation for huhohshdhjha
                                          a is an abbreviation for prsh
        [-t]                              show task information (implicitly -g t)
        [-u user_list]                    view only jobs of this user
        [-U user_list]                    select only queues where these users have access
        [-urg]                            display job urgency information
        [-pri]                            display job priority information
        [-xml]                            display the information in XML-Format

pe_list                  pe[,pe,...]
job_identifier_list      [job_id|job_name|pattern]{, [job_id|job_name|pattern]}
resource_list            resource[=value][,resource[=value],...]
user_list                user|@group[,user|@group],...]
resource_attributes      resource,resource,...
wc_cqueue                wildcard expression matching a cluster queue
wc_host                  wildcard expression matching a host
wc_hostgroup             wildcard expression matching a hostgroup
wc_qinstance             wc_cqueue@wc_host
wc_qdomain               wc_cqueue@wc_hostgroup
wc_queue                 wc_cqueue|wc_qdomain|wc_qinstance
wc_queue_list            wc_queue[,wc_queue,...]
invalid option argument "11"
```

The command needs to be `qstat -f -j PID`. I can't see anywhere in the logs where it prints out the `qstat` command that was used. Am I setting up the config incorrectly? this is `v0.999d`

It is SGE....

Kyle

**Comment by pcingola** [comment]
Hi Kyle,
  I've just updated the code to issue "qstat -f -j $jobPid" (for some reason the "-j" was removed 
and the command issued was "qstat -f $jobPid", which is the one used in MOAB instead SGE). 
  Also, the command is shown when using "-d".
  One comment: the "*additionalArgs" are added immediately after the command (so adding "-j" in your config would run "qstat -j -f $jobId" instead of "qstat -f -j $jobId").
  Please let me know if this is working for you.

**Comment by kmhernan** [comment]
Things seem to work better here. One thing that I am confused about is the checking job status procedure. Leaving the default `qstat` BDS is unable to find any job ID's. I thought about changing it to `qstat -f -j` but it also doesn't work (I understand that this is also wrong with regards to your functions). Regardless, the error from BDS is something like this:

```
00:02:07.020	Check task running:
	Command    : 'qstat -f -j'
	Exit value : 0
	Stdout     : scheduling info:            (Collecting of scheduler job information is turned off)


	Stderr     :
00:02:07.020	ExecutionerClusterSge 'ClusterSge[15]': Regex '' did NOT match line: 'scheduling'
```

When I leave it as the default just `qstat` it still can't parse the output. I see in your code that you look for some particular column ?? Could you please explain.

**Comment by pcingola** [comment]
If you can, please send me a sample of your qstat output (as a TXT file) and I'll debug it.
By default the procedure is:
   i-) Use first column (separated by "\\s+")
   ii-) Parse first column using pidRegex (form config file)
   iii-) Split first column by "\\." (dot) and use the first part

If none of these rules matches your qstat's output, I can try to add new rules or separate regex (in cds.config file) for parsing the jobIds.

**Comment by kmhernan** [comment]
Sure, here is the `qstat` output:

```
 job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
      1 0.55500 Test       ubuntu       r     01/26/2015 17:03:30 all.q@node001                      1
      2 0.00000 STDIN      ubuntu       qw    01/26/2015 17:03:35                                    1
      3 0.00000 STDIN      ubuntu       qw    01/26/2015 17:03:35                                    1
      4 0.00000 STDIN      ubuntu       qw    01/26/2015 17:03:35                                    1
      5 0.00000 STDIN      ubuntu       qw    01/26/2015 17:03:35                                    1
      6 0.00000 STDIN      ubuntu       qw    01/26/2015 17:03:35                                    4
      7 0.00000 STDIN      ubuntu       qw    01/26/2015 17:03:35                                    1
      8 0.00000 STDIN      ubuntu       qw    01/26/2015 17:03:35                                    1
      9 0.00000 STDIN      ubuntu       qw    01/26/2015 17:03:35                                    1
```

**Comment by pcingola** [comment]
This seems to work OK using the default settings. I didn't even have 
to set neither 'pidColumnCheckTaskRunning' nor 'pidRegexCheckTaskRunning' 
in my config file.

I've just added some debug messages, try running bds it using "-d" and 
it should show you the matching  IDs...

**Comment by kmhernan** [comment]
Ah, I just pulled the latest commits and re-ran as you requested. It looks like it's working:

```
00:01:03.528	ExecutionerClusterSge 'ClusterSge[31]': CheckTasksRunningCluster:Parsing line:	job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
00:01:03.528	ExecutionerClusterSge 'ClusterSge[31]': CheckTasksRunningCluster:	Adding ID (column number 0): 'job-ID'
00:01:03.529	ExecutionerClusterSge 'ClusterSge[31]': Regex '' did NOT match line: 'job-ID'
00:01:03.529	ExecutionerClusterSge 'ClusterSge[31]': CheckTasksRunningCluster:Parsing line:	-----------------------------------------------------------------------------------------------------------------
00:01:03.529	ExecutionerClusterSge 'ClusterSge[31]': CheckTasksRunningCluster:	Adding ID (column number 0): '---------------------------------------------------------------------------------------------------
--------------'
00:01:03.529	ExecutionerClusterSge 'ClusterSge[31]': Regex '' did NOT match line: '-----------------------------------------------------------------------------------------------------------------'
00:01:03.529	ExecutionerClusterSge 'ClusterSge[31]': CheckTasksRunningCluster:Parsing line:	6 0.50500 Test       ubuntu       r     01/27/2015 17:58:57 all.q@master                       1
00:01:03.529	ExecutionerClusterSge 'ClusterSge[31]': CheckTasksRunningCluster:	Adding ID (column number 0): '6'
00:01:03.530	ExecutionerClusterSge 'ClusterSge[31]': Regex '' did NOT match line: '6'
00:01:03.530	ExecutionerClusterSge 'ClusterSge[31]': CheckTasksRunningCluster:Parsing line:	7 0.60500 STDIN      ubuntu       r     01/27/2015 17:59:12 all.q@node001                      4
00:01:03.530	ExecutionerClusterSge 'ClusterSge[31]': CheckTasksRunningCluster:	Adding ID (column number 0): '7'
00:01:03.530	ExecutionerClusterSge 'ClusterSge[31]': Regex '' did NOT match line: '7'
00:01:03.530	ExecutionerClusterSge 'ClusterSge[31]': CheckTasksRunningCluster:Parsing line:	8 0.60500 STDIN      ubuntu       t     01/27/2015 17:59:12 all.q@node001                      4
00:01:03.530	ExecutionerClusterSge 'ClusterSge[31]': CheckTasksRunningCluster:	Adding ID (column number 0): '8'
00:01:03.530	ExecutionerClusterSge 'ClusterSge[31]': Regex '' did NOT match line: '8'
00:01:03.531	ExecutionerClusterSge 'ClusterSge[31]': CheckTasksRunningCluster:Parsing line:	9 0.60500 STDIN      ubuntu       r     01/27/2015 17:59:12 all.q@master                       4
00:01:03.531	ExecutionerClusterSge 'ClusterSge[31]': CheckTasksRunningCluster:	Adding ID (column number 0): '9'
00:01:03.531	ExecutionerClusterSge 'ClusterSge[31]': Regex '' did NOT match line: '9'
00:01:03.531	ExecutionerClusterSge 'ClusterSge[31]': CheckTasksRunningCluster:Parsing line:	10 0.60500 STDIN      ubuntu       qw    01/27/2015 17:58:59                                    4
00:01:03.531	ExecutionerClusterSge 'ClusterSge[31]': CheckTasksRunningCluster:	Adding ID (column number 0): '10'
00:01:03.531	ExecutionerClusterSge 'ClusterSge[31]': Regex '' did NOT match line: '10'
CheckTasksRunning.findRunningTaskByPid(99):	Found task PID '10'
CheckTasksRunning.findRunningTaskByPid(99):	Found task PID '7'
```

I think that the `Regex '' did NOT match line: 'job-ID'` was all that I was seeing before (just `-v -log`) and so I thought it was some error in the checking.

**Comment by pcingola** [comment]
If it seems to be working OK, I'll close this bug.
If you see the problem again, feel free to re-open.
